spring:
  application:
    name: ${app_name}
  datasource:
    url: ${db_conn_string}
    username: ${postgres_login}
    password: ${postgres_password}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      schema-locations: ${db_schema}
      mode: never
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    baseline-on-migrate: true
    validateMigrationNaming: true
    locations: classpath:db/migration
    default-schema: ${db_schema}
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  mail:
    host: smtp.yandex.ru
    port: 587
    username: ${email_tuz_word_app}
    password: ${email_tuz_word_app_pwd}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 5000

logging:
  level:
    org.flywaydb: DEBUG

jwt:
  secret: ${jwtSecret}
  lifetime: ${jwtSecretLifetime}