spring:
  application:
    name: ${app_name}
  datasource:
    url: ${db_conn_string}
    username: ${postgres_login}
    password: ${postgres_password}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      schema-locations: ${db_schema}
      mode: never
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show_sql: true
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    baseline-on-migrate: true
    validateMigrationNaming: true
    locations: classpath:db/migration
#    default-schema: ${db_schema}
    schemas: ${db_schema}
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  mail:
    host: smtp.yandex.ru
    port: 587
    username: ${email_tuz_word_app}
    password: ${email_tuz_word_app_pwd}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 5000

logging:
  level:
    org.flywaydb: DEBUG

jwt:
  secret: ${jwtSecret}
  lifetime: 30m
  refreshExpiration: 600m

registration:
  link: "https://localhost:8443/registration/submit?rt="
#  link: "http://localhost:8080/registration/submit?rt="
  textTemplate: "Привет! {0},
            
            Спасибо за регистрацию на нашем сервисе. Для завершения регистрации, пожалуйста, перейдите по следующей ссылке:
            
            {1}
            
            Если вы не запрашивали это письмо, пожалуйста, проигнорируйте его.
            
            С уважением,
            Команда сервиса"
  subject: Регистрация в Word App
  authCode:
    lifeTime: 30m

tts:
  api:
    cloud:
      yandex:
        token: ${YANDEX_TTS_TOKEN}
#server:
#  port: 8443
#  ssl:
#    enabled: true
#    key-store: ${wordAppKeystore}
#    key-store-password: ${wordAppKeystorePwd}
#    key-store-type: PKCS12


# Подключение к Яндекс.Объектному хранилищу (S3-совместимость)
cloud:
  aws:
    s3-access-key: ${s3-access-key}
    s3-secret-key: ${s3-secret-key}
    region: "ru-central1"
    s3-endpoint: "http://storage.yandexcloud.net"

  yandex:
    translation:
      jsonFileName: "D:\\code\\keys\\translation-api-key\\1.json"
    token-url: "https://iam.api.cloud.yandex.net/iam/v1/tokens"
    OAuth-token: ${yandex-oauth-token}

  log4j:
    logger:
      com:
        amazonaws:
            request: "DEBUG"
            response: "DEBUG"

